/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as TranscriptsRouteImport } from './routes/transcripts'
import { Route as SocioRouteImport } from './routes/socio'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OpsPredictiveRouteImport } from './routes/ops-predictive'
import { Route as OpsDispatchRouteImport } from './routes/ops-dispatch'
import { Route as OpsCameraRouteImport } from './routes/ops-camera'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GraphsRouteImport } from './routes/graphs'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as DossierRouteImport } from './routes/dossier'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as BoardRouteImport } from './routes/board'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AskRouteImport } from './routes/ask'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfilePersonIdRouteImport } from './routes/profile.$personId'

const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const TranscriptsRoute = TranscriptsRouteImport.update({
  id: '/transcripts',
  path: '/transcripts',
  getParentRoute: () => rootRouteImport,
} as any)
const SocioRoute = SocioRouteImport.update({
  id: '/socio',
  path: '/socio',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsPredictiveRoute = OpsPredictiveRouteImport.update({
  id: '/ops-predictive',
  path: '/ops-predictive',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsDispatchRoute = OpsDispatchRouteImport.update({
  id: '/ops-dispatch',
  path: '/ops-dispatch',
  getParentRoute: () => rootRouteImport,
} as any)
const OpsCameraRoute = OpsCameraRouteImport.update({
  id: '/ops-camera',
  path: '/ops-camera',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphsRoute = GraphsRouteImport.update({
  id: '/graphs',
  path: '/graphs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const DossierRoute = DossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardRoute = BoardRouteImport.update({
  id: '/board',
  path: '/board',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AskRoute = AskRouteImport.update({
  id: '/ask',
  path: '/ask',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfilePersonIdRoute = ProfilePersonIdRouteImport.update({
  id: '/profile/$personId',
  path: '/profile/$personId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/console': typeof ConsoleRoute
  '/dossier': typeof DossierRoute
  '/forecast': typeof ForecastRoute
  '/graphs': typeof GraphsRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/ops-camera': typeof OpsCameraRoute
  '/ops-dispatch': typeof OpsDispatchRoute
  '/ops-predictive': typeof OpsPredictiveRoute
  '/reports': typeof ReportsRoute
  '/socio': typeof SocioRoute
  '/transcripts': typeof TranscriptsRoute
  '/trends': typeof TrendsRoute
  '/vision': typeof VisionRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/console': typeof ConsoleRoute
  '/dossier': typeof DossierRoute
  '/forecast': typeof ForecastRoute
  '/graphs': typeof GraphsRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/ops-camera': typeof OpsCameraRoute
  '/ops-dispatch': typeof OpsDispatchRoute
  '/ops-predictive': typeof OpsPredictiveRoute
  '/reports': typeof ReportsRoute
  '/socio': typeof SocioRoute
  '/transcripts': typeof TranscriptsRoute
  '/trends': typeof TrendsRoute
  '/vision': typeof VisionRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/ask': typeof AskRoute
  '/audit': typeof AuditRoute
  '/board': typeof BoardRoute
  '/console': typeof ConsoleRoute
  '/dossier': typeof DossierRoute
  '/forecast': typeof ForecastRoute
  '/graphs': typeof GraphsRoute
  '/login': typeof LoginRoute
  '/network': typeof NetworkRoute
  '/ops-camera': typeof OpsCameraRoute
  '/ops-dispatch': typeof OpsDispatchRoute
  '/ops-predictive': typeof OpsPredictiveRoute
  '/reports': typeof ReportsRoute
  '/socio': typeof SocioRoute
  '/transcripts': typeof TranscriptsRoute
  '/trends': typeof TrendsRoute
  '/vision': typeof VisionRoute
  '/profile/$personId': typeof ProfilePersonIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/audit'
    | '/board'
    | '/console'
    | '/dossier'
    | '/forecast'
    | '/graphs'
    | '/login'
    | '/network'
    | '/ops-camera'
    | '/ops-dispatch'
    | '/ops-predictive'
    | '/reports'
    | '/socio'
    | '/transcripts'
    | '/trends'
    | '/vision'
    | '/profile/$personId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/audit'
    | '/board'
    | '/console'
    | '/dossier'
    | '/forecast'
    | '/graphs'
    | '/login'
    | '/network'
    | '/ops-camera'
    | '/ops-dispatch'
    | '/ops-predictive'
    | '/reports'
    | '/socio'
    | '/transcripts'
    | '/trends'
    | '/vision'
    | '/profile/$personId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/ask'
    | '/audit'
    | '/board'
    | '/console'
    | '/dossier'
    | '/forecast'
    | '/graphs'
    | '/login'
    | '/network'
    | '/ops-camera'
    | '/ops-dispatch'
    | '/ops-predictive'
    | '/reports'
    | '/socio'
    | '/transcripts'
    | '/trends'
    | '/vision'
    | '/profile/$personId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AskRoute: typeof AskRoute
  AuditRoute: typeof AuditRoute
  BoardRoute: typeof BoardRoute
  ConsoleRoute: typeof ConsoleRoute
  DossierRoute: typeof DossierRoute
  ForecastRoute: typeof ForecastRoute
  GraphsRoute: typeof GraphsRoute
  LoginRoute: typeof LoginRoute
  NetworkRoute: typeof NetworkRoute
  OpsCameraRoute: typeof OpsCameraRoute
  OpsDispatchRoute: typeof OpsDispatchRoute
  OpsPredictiveRoute: typeof OpsPredictiveRoute
  ReportsRoute: typeof ReportsRoute
  SocioRoute: typeof SocioRoute
  TranscriptsRoute: typeof TranscriptsRoute
  TrendsRoute: typeof TrendsRoute
  VisionRoute: typeof VisionRoute
  ProfilePersonIdRoute: typeof ProfilePersonIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transcripts': {
      id: '/transcripts'
      path: '/transcripts'
      fullPath: '/transcripts'
      preLoaderRoute: typeof TranscriptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/socio': {
      id: '/socio'
      path: '/socio'
      fullPath: '/socio'
      preLoaderRoute: typeof SocioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-predictive': {
      id: '/ops-predictive'
      path: '/ops-predictive'
      fullPath: '/ops-predictive'
      preLoaderRoute: typeof OpsPredictiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-dispatch': {
      id: '/ops-dispatch'
      path: '/ops-dispatch'
      fullPath: '/ops-dispatch'
      preLoaderRoute: typeof OpsDispatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ops-camera': {
      id: '/ops-camera'
      path: '/ops-camera'
      fullPath: '/ops-camera'
      preLoaderRoute: typeof OpsCameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphs': {
      id: '/graphs'
      path: '/graphs'
      fullPath: '/graphs'
      preLoaderRoute: typeof GraphsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dossier': {
      id: '/dossier'
      path: '/dossier'
      fullPath: '/dossier'
      preLoaderRoute: typeof DossierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/board': {
      id: '/board'
      path: '/board'
      fullPath: '/board'
      preLoaderRoute: typeof BoardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ask': {
      id: '/ask'
      path: '/ask'
      fullPath: '/ask'
      preLoaderRoute: typeof AskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$personId': {
      id: '/profile/$personId'
      path: '/profile/$personId'
      fullPath: '/profile/$personId'
      preLoaderRoute: typeof ProfilePersonIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AskRoute: AskRoute,
  AuditRoute: AuditRoute,
  BoardRoute: BoardRoute,
  ConsoleRoute: ConsoleRoute,
  DossierRoute: DossierRoute,
  ForecastRoute: ForecastRoute,
  GraphsRoute: GraphsRoute,
  LoginRoute: LoginRoute,
  NetworkRoute: NetworkRoute,
  OpsCameraRoute: OpsCameraRoute,
  OpsDispatchRoute: OpsDispatchRoute,
  OpsPredictiveRoute: OpsPredictiveRoute,
  ReportsRoute: ReportsRoute,
  SocioRoute: SocioRoute,
  TranscriptsRoute: TranscriptsRoute,
  TrendsRoute: TrendsRoute,
  VisionRoute: VisionRoute,
  ProfilePersonIdRoute: ProfilePersonIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
